name: DevOps-GitHubActions

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow depuis l'interface GitHub

jobs:
  # Build And deploy Job
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build Project
        run: npm run build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      # Deploy via FTP
      - name: FTP Deploy
        uses: ./my-actions/ftp-deploy
        with:
          server: ${{ secrets.FTP_SERVER }}
          port:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: ./dist
          remote_dir: ${{ secrets.FTP_REMOTE_DIR }}
