name: DevOps-GitHubActions

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet de déclencher manuellement le workflow depuis l'interface GitHub

jobs:
  # Build And deploy Job
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2  # Utilisation de l'action 'checkout' autorisée

      # 2. Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2  # Utilisation de l'action 'setup-node' autorisée
        with:
          node-version: '16'

      # 3. Debug Info
      - name: Debug Info
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "VITE_API_URL: $VITE_API_URL"  # Pas besoin de vars. pour les variables d'environnement
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
          echo "SERVER_PORT: ${{ secrets.SERVER_PORT }}"
          echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"
          echo "DEPLOYMENT_DIRECTORY: ${{ secrets.DEPLOYMENT_DIRECTORY }}"

      # 4. Install project dependencies
      - name: Install Dependencies
        run: npm install

      # 5. Build the project
      - name: Build Project
        run: npm run build
        env:
          VITE_API_URL: $VITE_API_URL

      # 6. Deploy via SSH
      # Remplacez cette étape par votre propre méthode de déploiement autorisée dans votre dépôt
      # Cette étape utilise une action externe, vous devrez la remplacer par une méthode approuvée.
      - name: Placeholder for Deployment
        run: echo "Deployment step"

# Vous devez remplacer cette étape par votre propre méthode de déploiement approuvée.
